### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by fheeze** [acch/XML-to-bootstrap#2]
Hi Acch, 

For some reason I cannot fully get it to work either on my Mac OS machine or my Windows computer. 

Would you have a detailed manual on how to easy set this up for Windows? 
I'd really like a version i could put on a USB-stick and edit the html in the publish map on any computer. 

My personal e-mail is fheeze@msn.com. Hope you can help me with setting this website up and making it easy to edit for me. 

Sorry i'm kinda novice (not in IT but in dev)

**Comment by acch** [comment]
In contact via email...

**Comment by acch** [comment]
I have simplified the Docker deployment process, made it more robust, and added details to the [README](/acch/XML-to-bootstrap/blob/master/README.md#container-deployment). Hope this helps...

All the best!
